name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: vcpkg install catch2

      - name: test access to core dump directory
        run: |
          sudo chmod -R +rwx /cores/*
          sudo touch /cores/test
          ls /cores
          sudo rm /cores/test

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          make all
      - name: Test
        run: |
          cd build
          ulimit -c unlimited
          sudo ctest --timeout 3000

      - name: chmod cores
        if: always()
        run: |
          sudo chmod -R +rwx /cores/*
          sudo touch /cores/test
          ls /cores
          sudo rm /cores/test

      - name: Upload core dumps
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: crashes
          path: /cores
      - name: Upload catch2 logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: catch2
          path: ./build/Testing/Temporary/
