name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - run: vcpkg install catch2

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          make all

      - name: Upload build
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build

      - name: Test
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd build
          ctest --timeout 3000

      - name: Upload catch2 logs
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: catch2
          path: ./build/Testing/Temporary/
